"""URG-based coverage backend.

Reads session.xml generated by ``urg -xml_verbose`` and serves scope-level
aggregate coverage data from memory.  Does not depend on pynpi/NPI for reads.
"""
from __future__ import annotations

import os
import subprocess
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from .backend import CoverageBackend
from .urg_runner import UrgRunner

Json = Dict[str, Any]


@dataclass
class UrgAggBackend(CoverageBackend):
    worker_kind = "urg_xml"

    vdb: str = ""
    cache_dir: Optional[str] = None
    queue: Optional[str] = None
    resource: Optional[str] = None
    exclusion_policy: str = "default"

    _xml_path: Optional[str] = field(default=None, init=False)
    _scopes: Dict[str, Json] = field(default_factory=dict, init=False)
    _metrics: List[str] = field(default_factory=list, init=False)
    _tests: List[Json] = field(default_factory=list, init=False)
    _top_scopes: List[Json] = field(default_factory=list, init=False)
    _loaded: bool = field(default=False, init=False)

    def __post_init__(self) -> None:
        if not self.vdb:
            raise ValueError("UrgAggBackend requires vdb path")

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        self._run_urg()
        self._parse_xml()
        self._loaded = True

    def _run_urg(self) -> None:
        if self.cache_dir is None:
            self.cache_dir = tempfile.mkdtemp(prefix=".xcov-urg-")
        xml_path = os.path.join(self.cache_dir, "session.xml")
        runner = UrgRunner(queue=self.queue, resource=self.resource)
        result = runner.run(
            ["urg", "-dir", self.vdb, "-report", self.cache_dir,
             "-format", "text", "-xml_verbose"],
            timeout=300,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"URG failed (exit {result.returncode}): {result.stderr[:500]}"
            )
        if not os.path.isfile(xml_path):
            raise RuntimeError(f"URG did not produce session.xml at {xml_path}")
        self._xml_path = xml_path

    def _parse_xml(self) -> None:
        tree = ET.parse(self._xml_path)
        root = tree.getroot()

        # Parse metrics definitions
        hvp = root.find("hvp")
        if hvp is not None:
            datadef = hvp.find("datadef")
            if datadef is not None:
                self._metrics = [
                    m.get("name", "")
                    for m in datadef.findall("metdef")
                    if m.get("builtin") == "1"
                ]

        # Parse scope tree
        old_cov = root.find("old_coverage")
        if old_cov is not None:
            self._scopes = {}
            self._parse_scopes(old_cov)

    def _parse_scopes(self, element, parent_name: str = "") -> None:
        for scope in element.findall("scope"):
            stype = scope.get("type", "")
            name = scope.get("name", "")
            full_name = name if not parent_name else f"{parent_name}.{name}" if parent_name != name else name

            if stype == "instance":
                metrics = {}
                for m in scope.findall("metric"):
                    mname = m.get("name", "")
                    val = m.get("value", "0/0")
                    excl = int(m.get("excl", 0))
                    if "/" in val:
                        covered_str, total_str = val.split("/", 1)
                        metrics[mname] = {
                            "covered": int(covered_str),
                            "coverable": int(total_str),
                            "excluded": excl,
                        }
                self._scopes[full_name] = {
                    "name": name,
                    "full_name": full_name,
                    "type": "instance",
                    "metrics": metrics,
                }
                # Track top scopes
                if parent_name == "" or parent_name == name:
                    self._top_scopes.append({"name": full_name, "full_name": full_name})

            # Recurse
            self._parse_scopes(scope, full_name)

    def invalidate(self) -> None:
        self._loaded = False
        self._scopes.clear()
        self._metrics.clear()
        self._top_scopes.clear()

    # ── CoverageBackend interface ──

    def close(self) -> None:
        self._loaded = False

    def tests(self) -> List[Json]:
        self._ensure_loaded()
        if not self._tests:
            return [{"name": "merged"}]
        return self._tests

    def summary(self) -> Json:
        self._ensure_loaded()
        return {
            "test_count": max(1, len(self._tests)),
            "top_scope_count": max(1, len(self._top_scopes)),
        }

    def top_scopes(self) -> List[Json]:
        self._ensure_loaded()
        result = []
        for s in self._top_scopes:
            leaf = s["name"].rsplit(".", 1)[-1]
            result.append({
                "name": leaf, "full_name": s["name"],
                "parent": None, "depth": 0, "type": "instance",
            })
        return result

    def scopes(self) -> List[Json]:
        self._ensure_loaded()
        all_names = set(self._scopes.keys())
        # Add intermediate ancestor scopes (e.g. generate blocks) so that
        # every scope's parent exists in the set.
        extra = set()
        for sname in all_names:
            parts = sname.split(".")
            for i in range(1, len(parts)):
                ancestor = ".".join(parts[:i])
                if ancestor not in all_names:
                    extra.add(ancestor)
        all_names |= extra

        result = []
        for sname in sorted(all_names):
            leaf = sname.rsplit(".", 1)[-1]
            parent = sname.rsplit(".", 1)[0] if "." in sname else None
            depth = sname.count(".")
            result.append({
                "name": leaf,
                "full_name": sname,
                "parent": parent,
                "depth": depth,
                "type": "instance",
            })
        if not result:
            return []
        return result

    _URG_TO_XCOV_METRIC = {
        "Line": "line", "Cond": "condition", "Toggle": "toggle",
        "FSM": "fsm", "Branch": "branch", "Assert": "assert",
    }
    _METRIC_SCORE_TYPE = {
        "line": "npiCovStmtBin", "condition": "npiCovConditionBin",
        "toggle": "npiCovToggleBin", "fsm": "npiCovTransBin",
        "branch": "npiCovBranchBin", "assert": "npiCovAssert",
    }

    def items(
        self,
        metrics: Optional[List[str]] = None,
        scope: Optional[str] = None,
        test: str = "merged",
        functional_only: bool = False,
    ) -> List[Json]:
        self._ensure_loaded()
        rows: List[Json] = []
        for sname, sdata in self._scopes.items():
            if scope and sname != scope and not sname.startswith(scope + "."):
                continue
            for urname, mdata in sdata["metrics"].items():
                mname = self._URG_TO_XCOV_METRIC.get(urname)
                if mname is None:
                    continue  # skip Group, Point, Cross etc.
                if metrics and mname not in metrics:
                    continue
                if functional_only and mname != "functional":
                    continue
                row: Json = {
                    "scope": sname,
                    "metric": mname,
                    "type": self._METRIC_SCORE_TYPE.get(mname, "npiCovStmtBin"),
                    "covered": mdata["covered"],
                    "coverable": mdata["coverable"],
                    "missing": max(0, mdata["coverable"] - mdata["covered"]),
                    "count": None,
                    "coverage_pct": (
                        round(100.0 * mdata["covered"] / mdata["coverable"], 4)
                        if mdata["coverable"] > 0 else None
                    ),
                    "status": (
                        ["covered"]
                        if mdata["coverable"] > 0 and mdata["covered"] >= mdata["coverable"]
                        else ["not_covered"]
                    ),
                    "evidence": {"file": None, "line": None},
                    "name": f"{sname}.{mname}",
                    "full_name": f"{sname}.{mname}",
                }
                # Type-specific required fields
                if mname == "assert":
                    row["assert_kind"] = "assertion"
                    row["assert_object"] = f"{sname}.{mname}"
                elif mname == "toggle":
                    row["toggle_signal"] = row["full_name"]
                    row["toggle_bit"] = row["full_name"]
                    row["toggle_transition"] = "aggregate"
                elif mname == "branch":
                    row["branch"] = row["full_name"]
                    row["branch_bin"] = "aggregate"
                elif mname == "condition":
                    row["condition"] = row["full_name"]
                    row["condition_bin"] = "aggregate"
                rows.append(row)
        return rows

    def load_exclusions(self, paths: List[str], test: str = "merged") -> List[Json]:
        return [{"path": p, "status": "not_supported_in_urg_backend"} for p in paths]

    def set_exclusion(
        self, coverage_ref: str, excluded: bool, test: str = "merged"
    ) -> Json:
        return {"coverage_ref": coverage_ref, "status": "not_supported_in_urg_backend"}

    def save_exclusions(self, path: str, test: str = "merged") -> None:
        pass  # managed by session.ensure_el_ready() via NPI

    def unload_exclusions(self, test: str = "merged") -> None:
        pass  # managed by session via NPI
